### ISSUE TITLE
Camera is not found

### ISSUE THREAD

**Issue by happychameleon** [flathub/org.signal.Signal#145]
When using the new video call feature signal can not find the camera.

**Comment by rgilton** [comment]
Same here.  If I run it with `flatpak run --device=all org.signal.Signal` then it works ok.  I assume there's some sort of flatpak config that could be done to make it work "out of the box" though.

**Comment by happychameleon** [comment]
Yeah I just created a pull request which copies what the zoom flatpak does which is essentially setting "--devices=all" in the flatpak manifest

**Comment by bermeitinger-b** [comment]
Do you know and understand the security implications of that flag? I suppose the devices are outside the sandbox for a reason.

**Comment by happychameleon** [comment]
Yeah It's less then ideal but I don't think there is another way of doing it without using portals. From the docs:

> ### [Device access](https://docs.flatpak.org/en/latest/sandbox-permissions.html?highlight=devices#device-access)
> While not ideal, `--device=all` can be used to access devices like controllers or webcams.

**Comment by happychameleon** [comment]
I guess using `--nodevice` we could remove kvm and shm from the accessible devices not sure how much that would improve things

**Comment by purpleidea** [comment]
It needs `--device=all` because the webcam portal isn't working for some reason. This defeats the point of a sandbox, and I thought this was implemented, see: https://github.com/flatpak/xdg-desktop-portal/issues/38

So I don't know the specifics, but my guess is that this is possibly related to pipewire not being hooked up to all of this yet. (It's not even stable or in distros yet.) It's supposed to come in the next 1.5 years for Fedora AIUI, so maybe by then. Until then, device=all.

HTH
