### ISSUE TITLE
Feature request: Stay in tray by default

### ISSUE THREAD

**Issue by yookoala** [flathub/org.signal.Signal#151]
Most IM application (e.g. Pidgin, Element, Telegram Desktop) supports staying in tray icon when closed. This would be a more common default behaviour.

According the [discussion here](https://github.com/signalapp/Signal-Desktop/issues/2210#issuecomment-380383841), Signal Desktop supports `--start-in-tray` or `--use-tray-icon` as startup argument that would enable that kind of behaviour. It would be great if the flatpak package have this enabled by default.

**Comment by salim-b** [comment]
I'd suggest to only add the `--use-tray-icon` to the [default `.desktop` file](https://github.com/flathub/org.signal.Signal/issues/116#issuecomment-589998170) shipped by the Flatpak. I guess a lot of users would be confused otherwise when trying to start Signal through the default launcher and it's doesn't open "in front" of them.

The user can always manually add the additional `--start-in-tray` flag to the respective autostart command.

**Comment by bermeitinger-b** [comment]
We would like to stick to the same upstream behavior. I suggest you put your request upstream and when they accept this change in default behavior, this will be inherited to here.

**Comment by yookoala** [comment]
@bermeitinger-b: May I ask where is the upstream?

**Comment by bermeitinger-b** [comment]
Upstream is here https://github.com/signalapp/Signal-Desktop

**Comment by bermeitinger-b** [comment]
Close by #152

**Comment by tjanez** [comment]
> Close by #152

Just for future reference, the PR was not accepted since:

_We would like to stick to the same behavior of the original program. The default desktop file from upstream does not have this parameter as default, so I prefer not to have it here as well._
(source: https://github.com/flathub/org.signal.Signal/pull/152#issuecomment-704944868)

**Comment by salim-b** [comment]
FYI: It looks like the Signal Desktop app will soon gain proper UI support to configure both `--use-tray-icon` and `--start-in-tray`, see https://github.com/signalapp/Signal-Desktop/pull/4827#pullrequestreview-598717928

**Comment by benjamin051000** [comment]
Hi, still having issues with this.

Linux fedora 5.18.7-200.fc36.x86_64
GNOME 42.2
Signal 5.48.0 flathub

neither `--use-tray-icon` or `--start-in-tray` worked for me at the end of the `Exec` line of `/var/lib/flatpak/app/org.signal.Signal/x86_64/stable/121cfe765e5ef9ecf3481a88268e7bc653b866b7cdb776ea0216e5548c082488/export/share/applications/org.signal.Signal.desktop`. Using [Tray Icons Reloaded](https://github.com/MartinPL/Tray-Icons-Reloaded) extension (Extension manager says V25 but GitHub says latest release was V24... weird).

**Comment by benjamin051000** [comment]
Running `flatpak run org.signal.Signal --use-system-tray` yields no text about the flag in the stdout.

**Comment by XenonSup** [comment]
> Hi, still having issues with this.
> 
> Linux fedora 5.18.7-200.fc36.x86_64 GNOME 42.2 (Wayland) Signal 5.48.0 flathub

Hi, I'm on basically the same platform.

> neither `--use-tray-icon` or `--start-in-tray` worked for me at the end of the `Exec` line of `/var/lib/flatpak/app/org.signal.Signal/x86_64/stable/121cfe765e5ef9ecf3481a88268e7bc653b866b7cdb776ea0216e5548c082488/export/share/applications/org.signal.Signal.desktop`. Using [Tray Icons Reloaded](https://github.com/MartinPL/Tray-Icons-Reloaded) extension (Extension manager says V25 but GitHub says latest release was V24... weird).

I got it to work by editing
`/var/lib/flatpak/exports/share/applications/org.signal.Signal.desktop`,
_not_ the file under the `/app/` directory.

Additionally it also works for me if I run `flatpak run org.signal.Signal --use-tray-icon` not `--use-system-tray`
