### ISSUE TITLE
Filesystem access scope

### ISSUE THREAD

**Issue by yookoala** [flathub/org.signal.Signal#153]
Is there any reason why this application needs a full "home" filesystem access? If the file system access is only for downloading files, the access scope can well just be "[xdg-download](https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access)" (the download folder) instead of "[home](https://github.com/flathub/org.signal.Signal/blob/aa106ec6a68642e4f065a6cc2c0c1faea22d4bb0/org.signal.Signal.json#L20)", right?

The [Element / Riot.im](https://flathub.org/apps/details/im.riot.Riot) flatpak package is [setup this way](https://github.com/flathub/im.riot.Riot/blob/4ab4989fac405763f35f86b2e3785c62c04949ac/im.riot.Riot.json#L18).

**Comment by bermeitinger-b** [comment]
The application needs access to home, so that sharing files with your contacts will stay possible.

**Comment by bermeitinger-b** [comment]
There seems to be a possibility to circumvent the restrictions.
https://github.com/flathub/org.signal.Signal/pull/154#issuecomment-717866785
I can partially verify this, however, did you look at the sent passwd file? It is the one from the sandboxed environment and not the host system.

**Comment by yookoala** [comment]
Strange. I am a GNOME user and I don't experience this issue. Could this be a DE specific bug?

**Comment by yookoala** [comment]
![2020-10-29 08-56-27 的螢幕擷圖](https://user-images.githubusercontent.com/91274/97512513-ab1cae00-19c4-11eb-8d1f-c1c07fcbfd03.png)

The file sharing screen for the latest version of Flatpak-installed Signal.

The Chinese folder names read:

- 圖片 (Pictures)
- 下載 (Downloads)
- 桌面 (Desktop)
- 影片 (Videos)
- 音樂 (Musics)
- 文件 (Documents)
- 分享 (Shared)

**Comment by yookoala** [comment]
As described here:
* https://github.com/flathub/org.signal.Signal/pull/154#issuecomment-718308338
* https://github.com/flathub/org.signal.Signal/pull/154#issuecomment-718362833

I am unable to reproduce the issue in a virtual machine and a flesh-installed Kubuntu / KDE Neon. Both setups work perfectly normal to me.

**Comment by Maltimore** [comment]
This issue can be closed, as @yookoala convinced me successfully that the issue must be on my end.  Thanks @yookoala !

**Comment by dreua** [comment]
I only see the folders "Download" and "Desktop" because I deleted the others a long time ago, never thought they would be of any use until now. Makes me wonder if @Maltimore could have deleted/renamed all of them so they don't show up.

In general I think this would be a perfect use case for the [FileChooser portal](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.FileChooser). ([General description of portals.](https://docs.flatpak.org/en/latest/sandbox-permissions.html#portals))
Unfortunately I haven't used this before, has anyone experience or did some investigation whether using portals would be possible with Signal?

(Supporting drag and drop would be a dream! More info on that possibility: https://github.com/flatpak/xdg-desktop-portal/issues/99)
