### ISSUE TITLE
CromeOS Debian VM: Opens with blank dialog, no UI

### ISSUE THREAD

**Issue by jwishnie** [flathub/org.signal.Signal#163]
Installs and runs, but shows blank UI.

- Debian 10
- CrOS: 86.0.4240.198

![Screenshot 2020-11-23 at 11 39 54](https://user-images.githubusercontent.com/62867/100007770-67c61d00-2d81-11eb-908b-e6e90c42dd8d.png)

**Comment by rkjnsn** [comment]
I'm seeing the same issue with the flatpak on CrOS Version 87.0.4280.142 (Official Build) (64-bit).

The VSCode flatpak (which I believe is also Electron based) renders properly, as does Signal Desktop when installed from the Debian repository instead of using flatpak.

If I move the cursor slowly around the blank window in the flatpak, there are a couple of places where it turns to a text I-beam cursor, so it seems like the window is alive, it just never paints for some reason.

I don't see any clues in the console output as far as what might be going wrong, unfortunately.

**Comment by tarpin** [comment]
The same problem is on Fedora Silverblue.
It seems to be related to this issue: https://github.com/signalapp/Signal-Desktop/issues/4040
Setting the environment variable `QT_X11_NO_MITSHM=1` does not work.

**Comment by TLATER** [comment]
I have a similar problem (no window appears though, presumably because my WM doesn't render anything), it seems to work when given the `--no-sandbox` flag though - any chance one of you could check that's the problem? Should be easy to fix if so.

**Comment by jwishnie** [comment]
After updating to Flatpak 1.10.1 via buster-backports, and reinstalling the Signal Flatpak, it is running correctly, even without --no-sandbox
