### ISSUE TITLE
Excessive disk usage?

### ISSUE THREAD

**Issue by Frivolous2** [flathub/org.signal.Signal#178]
Signal writes 135GiB in the span of a day...?

![Capture d’écran de 2021-03-17 15-53-48](https://user-images.githubusercontent.com/57101103/111479499-ee37ad80-8728-11eb-8d3a-f35d67bc3901.png)
![Capture d’écran de 2021-03-17 15-58-11](https://user-images.githubusercontent.com/57101103/111479524-f1cb3480-8728-11eb-95f6-5564817584f2.png)

Signal Version:1.40.1
Operating System: Fedora 33
Linked Device Version: Android 5.4.12

Link to Debug Log
https://debuglogs.org/5516cd674f7799d67e346f08b820be43e4f7cad8621ce1766de8d1f6f3e2640f

**Comment by metal3d** [comment]
It's probably not here you should give this bug, but in Signal repo here: https://github.com/signalapp/Signal-Desktop/issues

Anyway, Signal write 640Mo a day on my side.
![image](https://user-images.githubusercontent.com/100080/112485319-1784b900-8d7b-11eb-9a67-1c183253b054.png)

**Comment by Frivolous2** [comment]
https://github.com/signalapp/Signal-Desktop/issues/5105
They sent me here 😅

**Comment by bermeitinger-b** [comment]
I don't know if this is flatpak related to upstream. 
The flatpak version does only wrap the original deb package, so I doubt it'll be a specific flatpak problem but to cross that from the list, I also recommend the official response https://github.com/signalapp/Signal-Desktop/issues/5105#issuecomment-802263266 and check if it also happens when not using the flatpak version.

**Comment by Frivolous2** [comment]
I'm using the flatpak version because I couldn't find an official .rpm version...
I guess I'll try to reproduce this on a VM
