### ISSUE TITLE
Enable --socket=wayland

### ISSUE THREAD

**Issue by kaimast** [flathub/org.signal.Signal#188]
Since Signal 5.1 there is experimental support for Wayland (see https://github.com/signalapp/Signal-Desktop/issues/3411).

Can we change the permissions of the flatpak to allow connecting to the Wayland server?

**Comment by hfiguiere** [comment]
You can try it yourself, but if this is experimental it's probably not a wise idea to enable it for all.

**Comment by kaimast** [comment]
You still need to enable ozone in the command line. This would just make it a little easier to do so.

**Comment by bermeitinger-b** [comment]
Does this have any influence into non-wayland sessions?

**Comment by Arxcis** [comment]
> You can try it yourself, but if this is experimental it's probably not a wise idea to enable it for all.

I agree. I think having both `--socket=wayland` and `--socket=x11` enabled at the same time would be confusing, because it is not obvious which one of the sockets Signal is actually using, or if it uses both. 

As long as wayland is not default, I think we should expect those who want to experiment, to run the override commands themselves:
```shell
flatpak override --user --socket=wayland org.signal.Signal
flatpak override --user --nosocket=x11   org.signal.Signal
```

... or use Flatseal:
![image](https://user-images.githubusercontent.com/3092618/119103417-6e290f00-ba1b-11eb-8c66-0318c48e3ab9.png)

Result in `~/.local/share/flatpak/overrides/org.signal.Signal`:
```
$ cat ~/.local/share/flatpak/overrides/org.signal.Signal 
[Context]
sockets=!x11;wayland;
```

**Comment by der-eismann** [comment]
Is there any progress on this? Just enabling the socket shouldn't have any effect because you still need to set additional flags to run signal on Wayland.
