### ISSUE TITLE
Enable tray icon

### ISSUE THREAD

**Issue by yselkowitz** [flathub/org.signal.Signal#242]
This is done by passing `--use-tray-icon` to signal in the Exec command line in the desktop file.

**Comment by bermeitinger-b** [comment]
Is the tray icon automatically activated in upstream's version and does flatpak somehow disable it?

Otherwise, I'd like to be to be as close to upstream as possible.

**Comment by salim-b** [comment]
> Is the tray icon automatically activated in upstream's version and does flatpak somehow disable it?

No, the upstream Linux version (DEB) starter cmd is: `/opt/Signal/signal-desktop --no-sandbox %U`

But I still think it's weird for a messenger app to not activate the tray icon by default... a bit unfortunate that users who want the tray have to mess with CLI args that way.

**Comment by Parent5446** [comment]
FWIW I just switched from using Signal from Snapcraft to Flatpak, and the tray icon went from working to not working. Not sure what Snap is doing differently though.

**Comment by Altonss** [comment]
> This is done by passing `--use-tray-icon` to signal in the Exec command line in the desktop file.

When using this it works with flatpak! But I only have one visual "bug", I don't know if it's specific to the flatpak: When the tray icon get updated (e.g. from one unread message, to no unread message), between the 2 different icons I get for a fraction of a second "..." (3 dots) instead of the Signal logo.

**Comment by Parent5446** [comment]
For reference after I've done more research:

https://github.com/signalapp/Signal-Desktop/issues/2210#issuecomment-872330273
https://github.com/signalapp/Signal-Desktop/issues/1965

Seems it is intentionally disabled by default for testing reasons.

That said, I think generally speaking it'd be nice for the Flatpak version if there was an environment variable it could read from to just take arbitrary CLI options, that way someone could manipulate the CLI options at their discretion using Flatseal or similar. (Otherwise we're just left to editing `signal-desktop.sh` manually every time the package updates.)

**Comment by bermeitinger-b** [comment]
You could try the test here: https://github.com/flathub/org.signal.Signal/pull/283 

If you set SIGNAL_USE_TRAY_ICON, it will add the `--use-tray-icon` upon starting.

**Comment by bermeitinger-b** [comment]
With #283, you can set the two variables:

* `SIGNAL_USE_TRAY_ICON`: Enables tray icon (effectively, adds `--use-tray-icon` to command)
* `SIGNAL_START_IN_TRAY`: Starts signal in tray (effectively, adds `--start-in-tray` to command)

**Comment by bermeitinger-b** [comment]
Upstream doesn't have it as default and we stick to upstream as close as possible.

**Comment by d4f5409d** [comment]
> Upstream doesn't have it as default and we stick to upstream as close as possible.

But if you made only a little toggle in the settings? Pleasie.

**Comment by bermeitinger-b** [comment]
Which settings? There are no flatpak specific settings.

Please ask upstream if they add a setting for this if you want it.
