### ISSUE TITLE
Signal did not start

### ISSUE THREAD

**Issue by wolfgang-58** [flathub/org.signal.Signal#265]
Good morning,
When starting in the terminal, the following error is displayed and signal does not start.
```
 /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=signal --file-forwarding org.signal.Signal @@u %U @@
bwrap: execvp signal: No such file or directory
```
Deleting "command=signal" starts Signal again.
greetings
Wolfgang

**Comment by jahed** [comment]
Same issue. You can downgrade for now.

```
sudo flatpak update --commit=d893803877b517bf74fdd75cc29da56bcb5fdf100c6d3ae8ea29d20fdd47b50a org.signal.Signal
flatpak mask org.signal.Signal # disable updates
```

**Comment by bermeitinger-b** [comment]
What specific environment do you have?
Maybe something with Wayland?

Or an outdated flatpak version?

**Comment by jahed** [comment]
@bermeitinger-b That makes sense. (Some?) Wayland users currently have to create a custom menu entry to get Signal working.

```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=signal-desktop --file-forwarding org.signal.Signal --disable-gpu @@u %U @@
```

Note the "--disable-gpu". Since we're using custom entries, the `command` change you mentioned wouldn't be applied so it's breaking it. I assume a lot of Wayland users will encounter this issue.

I've updated to latest with the new command in my menu entry and it's working. Is it possible to publish with `--disable-gpu` applied for Wayland to avoid these sorts of issues?

I'm on Fedora 35, Wayland, NV134, up-to-date.

**Comment by joulester** [comment]
I have the same problem on Pop os 21.10 but I don't have Wayland enabled. I can at least start it with @jahed command from terminal.

**Comment by bermeitinger-b** [comment]
Closed in favor of #269

**Comment by genodeftest** [comment]
@bermeitinger-b : You didn't close this issue. Is this by accident?

**Comment by bermeitinger-b** [comment]
I thought I did.
