### ISSUE TITLE
Cannot download multiple images at the same time

### ISSUE THREAD

**Issue by hamishmb** [flathub/org.signal.Signal#320]
Reporting here as I'm using the Flatpak version, as instructed by the Signal issue system. Happy to also report upstream if that's what I need to do.

Unlike on mobile, I can only download images one at a time on desktop. I'm assuming this is meant to be supported, but the option isn't present anywhere as far as I can tell.

### Platform Info

Signal Version:

5.47.0 (production).

Operating System:

Linux Mint 20.3 Cinnamon 64-bit.

Linked Device Version:

Android, Version 11.

**Comment by Cerberus0** [comment]
This is an upstream issue because, like [a few other features](https://community.signalusers.org/t/12003), this functionality just hasn't been implemented in Signal Desktop yet. However, the upstream Signal Desktop issue tracker is [only meant for bug reports](https://github.com/signalapp/Signal-Desktop/issues/5541), so the Signal community is tracking the implementation of this feature on the community forum:

https://community.signalusers.org/t/multi-select-and-save-media-to-disk/11962

Feel free to close this issue and continue the discussion on the Signal community forum, which you can easily join with your existing GitHub account.

**Comment by hamishmb** [comment]
Cheers, will do :)
