### ISSUE TITLE
Cursor problem on flatpak due to upstream

### ISSUE THREAD

**Issue by ghost** [flathub/org.signal.Signal#349]
Since last update and the usage of org.freedesktop.Platform/x86_64/22.08 cursor do not follow the one from the system anymore
and on hidpi screen on wayland the mouse is barely visible.

I tell this here because i don't have figured out where to report it to freedesktop.

so temporary fix for this signal app rollback to 21.08 time they fix it.

**Comment by bermeitinger-b** [comment]
Are you sure it's the 22.08 version and not any of the other wayland-related changes from the last updates?

Anyhow, Wayland is experimental with Electron.

**Comment by joshua-stone** [comment]
I only seem to notice a change in cursor size when `SIGNAL_USE_WAYLAND=1` is set.

```
$ distro 
Name: Fedora Linux 36.20220910.0 (Silverblue)
Version: 36
Codename: 
$ rpm -q gnome-shell flatpak
gnome-shell-42.4-1.fc36.x86_64
flatpak-1.12.7-5.fc36.x86_64
```

@BirdInFire Can you provide more details about your system?

**Comment by joshua-stone** [comment]
Since it's likely a regression in the Freedesktop runtime, then this is likely the best place to file an issue:

https://gitlab.com/freedesktop-sdk/freedesktop-sdk

**Comment by joshua-stone** [comment]
`org.freedesktop.Sdk` is for building the flatpak, while `org.freedesktop.Platform` is for the runtime. Both are provided in the same project, so issues could be filed for either component:

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/README.md#available-runtimes

As far as I know the regression should be in `org.freedesktop.Platform` since the flatpak build step does little more than repack a deb package:

https://github.com/flathub/org.signal.Signal/blob/6242c0a665878eb3016785b8c6cc9a712b484359/org.signal.Signal.yaml#L51

**Comment by joshua-stone** [comment]
A lot of the issues there seem to be mostly organization-level issues:

https://gitlab.freedesktop.org/freedesktop/freedesktop/-/issues/?state=all


@BirdInFire I think you should file a bug in the SDK bug tracker anyway. At the very least this regression will get more visibility, and the worst that could happen is that you'd be redirected to a different bug tracker.

**Comment by nanonyme** [comment]
@BirdInFire that repo is completely wrong place and in no way related to the runtime. https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues is the right project

**Comment by joshua-stone** [comment]
@BirdInFire I've filed an issue here:

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1484
