### ISSUE TITLE
Fail to download PDF

### ISSUE THREAD

**Issue by Altonss** [flathub/org.signal.Signal#719]
On latest version 7.25.0, the Gnome file-picker doesn't show the files and folder of the home directory when trying to download a file.
Nonetheless, after clicking on save no error is displaying, what should indicate a successful download. But  the downloaded file (tested with a PDF file) cannot be found.
Before this version (AFAIK), the downloads where behaving fine.

**Comment by bermeitinger-b** [comment]
Through the portals, it should be possible without explicitly allowing specific folders.

**Comment by bermeitinger-b** [comment]
I guess something broke, I can reproduce. Attaching and downloading files does not work. Seems like it doesn't use the portals.

If I try, for example, with LibreWolf, which has similar permissions, it does actually use the portal. So, I doubt it's a host problem. Seems like Electron is doing something wrong here.

**Comment by pm4rcin** [comment]
It's a regression of this version definitely since it has worked fine before.

**Comment by bermeitinger-b** [comment]
It works with the previous version. I'll revert.

**Comment by xduugu** [comment]
Given that apparently it's [no regression, but the intended behavior](https://github.com/electron/electron/issues/43819#issuecomment-2383104130), will you, @bermeitinger-b, merge the signal updates again? I currently use #762 with `--filesystem=xdg-download` and I guess, because electron now depends on an unreleased version of the file chooser portal, adding filesystem access is the way to go as it will take a long time until the future xdg-desktop-portal release is packaged for all the "stable" distributions.

**Comment by bermeitinger-b** [comment]
Looks like it's inevitable to make the Flatpak users angry once more.

**Comment by dimitris-personal** [comment]
> Looks like it's inevitable to make the Flatpak users angry once more.

True, bess bad than 3 releases behind and counting...

**Comment by bermeitinger-b** [comment]
Now, it's 4.

At this point, I'd rather open all of host instead of the myriad of xdg-* folders which we had already at some point.

**Comment by bermeitinger-b** [comment]
Sure, but typically people attach photos, so xdg-pictures should also be included, and videos, and people don't stick to the rules and store their pictures anywhere, so they will end up here asking why they can't attach certain files.
(I'm one of these, sometimes I dare to send a file from my `/tmp` directory.)

This is why the portals are so nice. But they decided they don't want us to have nice things. I vote for host file system, maybe with a warning to use Flatseal if they don't trust Signal 🤷

**Comment by xduugu** [comment]
> `xdg-downloads` folder could be enough as a temporary solution, no?

I guess *temporary* will be a long time, at least until the next ubuntu lts release.

> This is why the portals are so nice. But they decided they don't want us to have nice things. I vote for host file system access, maybe with a warning to use Flatseal if they don't trust Signal 🤷

The average user will probably expect at least `--filesystem=home`. Everybody who cares about the filesystem access will disable it anyway, so `host` or `home` access imo does not make much of a difference.

**Comment by bermeitinger-b** [comment]
Thanks for your opinion! See #766

**Comment by pm4rcin** [comment]
Also for desktop users giving `home` or `host` doesn't make any difference from security standpoint since people have their precious files somewhere in `home` so `host` isn't that useful IMO. And because both break the sandbox I'd go for `host` even though I dislike it very much but until electron devs reconsider their decision it's necessary for most people.

**Comment by bermeitinger-b** [comment]
Added with #766

**Comment by sukahiroaki** [comment]
Just pointing out that XDG Desktop Portal 1.19 has just been released (which would be recent enough for getting back to the proper behaviour). Not sure you want to use it though given that it is a development version. Still good to see that we are on a path to get a proper fix in the hopefully not too distant future

https://github.com/flatpak/xdg-desktop-portal/releases/tag/1.19.0
